### ISSUE TITLE
[SiliconAttack] - [ZJU_ZhangHaonan] - [Questions about the system prompts]

### ISSUE THREAD

**Issue by HotBento** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#10]
Do you add system prompts during the evaluation period?
For example, do you add '[INST]', '[/INST]', '\<s\>\</s\>' or '\<\<SYS\>\>' in the evaluation period?
If so, what's the format of the system prompts?

**Comment by nonstopfor** [comment]
I have similar questions. It seems that our local manual evaluation results differ significantly from the online evaluation results. I'm not sure whether this is due to differences in prompt format or evaluation standards.

**Comment by aisg-py** [comment]
Thank you for the queries. 

All essential information required for successful participation in the challenge has already been provided on the challenge portal and submission guide.
