### ISSUE TITLE
[Da Best Team] - [Errorman23] - [Question on prompt filtering/pre-processing]

### ISSUE THREAD

**Issue by Errorman23** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#11]
We'd like to check: will our submission JSON file be filtered/pre-processed in anyway before being passed to the victim LLMs?

For example, by default for track 1A, will any non-ASCII characters be trimmed out from each prompt before it's passed to victim LLMs for response generation?

Or, will '\\' be escaped again ('\\n' becomes '\\\n') before passing to the victim LLMs?

Further more, will this additional filtering/pre-processing layer be an available option for track 2 (defense) teams later on?

**Comment by aisg-py** [comment]
Hi @Errorman23 ,

The submission will be parsed according to the conventions of the JSON format, and the prompts thus parsed will be sent to the Victim Models for a response.

**Comment by Errorman23** [comment]
> Hi @Errorman23 ,
> 
> The submission will be parsed according to the conventions of the JSON format, and the prompts thus parsed will be sent to the Victim Models for a response.

Hi thanks for the reply. So is it correct to understand as that there're no filtering/pre-processing step before prompt strings are passed to victim LLM?

**Comment by mtmak-aisg** [comment]
I think that @aisg-py has answered the question.  Closing issue.
