### ISSUE TITLE
[Team-Badass] - [Yichuan_Mo] - [How is the quota calculated?]

### ISSUE THREAD

**Issue by mo666666** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#13]
Dear organizers, 
Thank you for organizing this interesting competition. My question is how the quota of submission is calculated. Does it calculated from the starting date of the competition or the date of the first submission? 
Thank you for your reply!

**Comment by aisg-py** [comment]
Hi @mo666666 
We adhere to the submission guideline clause 7F in the [Terms and Conditions](https://gcss.aisingapore.org/terms-and-conditions) for the submission quota.

Additionally, while clause 7E outlines that teams are entitled to a maximum of thirty (30) submissions throughout each Track phase, it is regulated by the aforementioned submission frequency detailed in clause 7F.

**Comment by mo666666** [comment]
Oh, thank you for your kind reminding. My concerns have been well addressed. I will closed this issue.
