### ISSUE TITLE
[suibianwanwan] - [SryButIKant] - [Quota and exclusion of previous submission]

### ISSUE THREAD

**Issue by Cthollist9** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#15]
![image](https://github.com/user-attachments/assets/fce85bdb-8e3b-46a1-ab0a-a4450ea98da7)
This note says that "contact an admin if you wish to raise a case to exclude a previous submission", does it mean I can exclude some submissions to get back some submission quota?
If so, then which type of submission can I exclude and how can I contact the admin?

**Comment by aisg-py** [comment]
You may attempt to raise a case to exclude a previous submission if you can demonstrate that a technical issue on our end is at fault, but this is subjected to both our investigation and final judgement, with no guaranteed time frame of response.

**Comment by Cthollist9** [comment]
![image](https://github.com/user-attachments/assets/5f4d580f-2d2e-4a5e-a2bf-21721a8b77cb)
can I exclude this submission? and how to raise this exclusion?

**Comment by aisg-py** [comment]
We have investigated and this submission does not warrant an exclusion for submission.
