### ISSUE TITLE
[suibianwanwan] - [SryButIKant] - [Randomness of responses from victim model]

### ISSUE THREAD

**Issue by Cthollist9** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#16]
Are the model responses deterministic (i.e. using greedy decode) or sampled? If they are sampled, then what is the random seed?

**Comment by aisg-py** [comment]
Your attack should be general enough that it does not require the victim models to behave deterministically.

**Comment by Cthollist9** [comment]
I mean, the do_sample options of LLAMA2-7b-Chat and vicuna are both `False` by default (meaning greedy decoding and deterministic response given a certain input) when using transformers for inference, so I wonder the corresponding settings of your online inference.

**Comment by Cthollist9** [comment]
Can we know that whether the online inference use transformers or FastChat, or something else?

**Comment by aisg-py** [comment]
All essential information required for successful participation in the challenge has already been provided on the challenge portal and submission guide.
