### ISSUE TITLE
[justdoit] - [justdoit] - [Question about track1b's submission]

### ISSUE THREAD

**Issue by Kris-Lcq** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#17]
![image](https://github.com/user-attachments/assets/49765e3d-835e-452c-9417-909092bb92d5)
Does this means, in track 1B,we do not know the 25 behaviors.  We just submmit our method to organizers and the organizers use our method to generate the attack prompt for every behaviors and finally test on llms.

**Comment by aisg-py** [comment]
This is correct. However, please note that we reserve the right to amend any details regarding Track 1B prior to its start.
