### ISSUE TITLE
ModelCrackers - yangjunx21 - Evaluation Exception

### ISSUE THREAD

**Issue by yangjunx21** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#18]
Could you please review our team's latest submission (Submission 10)? I have thoroughly examined the output and other details of this submission. However, I noticed that while the ASR for vicuna is at 92%, llama2's ASR shows 0. This submission closely resembles the previous two submissions, so I suspect there might have been an exception during the evaluation. Therefore, I kindly request re-evaluation. Thank you.

**Comment by aisg-py** [comment]
We have reviewed your submission 10 and confirmed that there are no issues on our end. The ASR results are accurate.

**Comment by yangjunx21** [comment]
Thank you for your effort. This is a very interesting result.
