### ISSUE TITLE
[SiliconAttack] - [ZJU_ZhangHaonan] - [Upload Error]

### ISSUE THREAD

**Issue by HotBento** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#19]
![image](https://github.com/user-attachments/assets/ca96b7cc-3690-4a02-bf28-2fa10fda3d53)

Hi! We accidentally failed in uploading the result. Could you please help us to remove this upload and return the quota?

**Comment by aisg-py** [comment]
Apologies, this is not possible.

**Comment by HotBento** [comment]
> Apologies, this is not possible.

Ok. Thank you. : )
