### ISSUE TITLE
[ateam] - [eyuansu62] - [Track 1A final rank]

### ISSUE THREAD

**Issue by HamLaertes** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#20]
Hi,

I wonder if you have the plan to announce the final rank which is based on ASRs of the two disclosed LLMs and the one undisclosed LLM?

Thanks!

**Comment by aisg-py** [comment]
As replied via email. Thanks!

**Comment by nonstopfor** [comment]
Could you also send this result to our (team [ModelCrackers]) email? Thanks!

**Comment by aisg-py** [comment]
As mentioned, we are not disclosing the Track 1A private leaderboard results at this moment.
