### ISSUE TITLE
For Track 1A, prompts must be generated from a model?

### ISSUE THREAD

**Issue by Errorman23** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#3]
The Challenge Overview mentioned: "**Track 1A:** Participants will be tasked with developing an **automatic attack model** capable of eliciting 50 predefined malicious behaviours from two open-sourced models."

However the submission file is only a JSON, does that mean the prompts could also be hand crafted?

**Comment by aisg-py** [comment]
Hi @Errorman23 , 

Track 1A strictly requires the use of automated methods to generate jailbreak prompts. You may wish to refer to [this page](https://gcss.aisingapore.org/background) for more information. 

We will verify the data and code bases for the top ten teams of Track 1A. 

For future questions, kindly also adhere to the guidelines for submitting questions [here](https://github.com/AISG-Technology-Team/GCSS-Track-1A-Submission-Guide/issues/1). Thank you.
