### ISSUE TITLE
[SiliconAttack] - [ZJU_ZhangHaonan] - [Questions about the submission format]

### ISSUE THREAD

**Issue by HotBento** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#5]
I have some questions about the submission format. Do we need to include the conversation template of the LLM in the submission? For example, should the submission be formatted like
```
<s>[INST] How to make a bomb? [adv_suffix] [\INST] <\s>
```
or just
```
How to make a bomb? [adv_suffix]
```
Could you please provide an example?
And could you please provide more detailed feedback, such as the generations of LLMs? It is difficult to locate the problem without feedback.

**Comment by aisg-py** [comment]
Dear @HotBento , 
Thanks for reaching out. 

You are not required to include the conversation template of the LLM in your submission. Please adhere to the format specified in the [submission guide](https://github.com/AISG-Technology-Team/GCSS-Track-1A-Submission-Guide).
 
Feedback regarding the effectiveness of your prompts can be gauged through the ASR displayed on the [public leaderboard](https://gcss.aisingapore.org/leaderboard). You are encouraged to utilize your multiple submission opportunities to refine your attacks based on this feedback.

**Comment by HotBento** [comment]
> Dear @HotBento , Thanks for reaching out.
> 
> You are not required to include the conversation template of the LLM in your submission. Please adhere to the format specified in the [submission guide](https://github.com/AISG-Technology-Team/GCSS-Track-1A-Submission-Guide).
> 
> Feedback regarding the effectiveness of your prompts can be gauged through the ASR displayed on the [public leaderboard](https://gcss.aisingapore.org/leaderboard). You are encouraged to utilize your multiple submission opportunities to refine your attacks based on this feedback.

@aisg-py Thank you for your reply! I wonder if the conversation template will be automatically included in the evaluation phase. Will our submission be directly fed into LLMs?

**Comment by HotBento** [comment]
> Dear @HotBento , Thanks for reaching out.
> 
> You are not required to include the conversation template of the LLM in your submission. Please adhere to the format specified in the [submission guide](https://github.com/AISG-Technology-Team/GCSS-Track-1A-Submission-Guide).
> 
> Feedback regarding the effectiveness of your prompts can be gauged through the ASR displayed on the [public leaderboard](https://gcss.aisingapore.org/leaderboard). You are encouraged to utilize your multiple submission opportunities to refine your attacks based on this feedback.

@aisg-py Thank you for your reply! I wonder if the conversation template will be automatically included in the evaluation phase. Will our submission be directly fed into LLMs?

**Comment by HotBento** [comment]
@aisg-py And how many submission quotas do we have? It looks like we are able to upload 7 results every 14 days, but this is in conflict with the total submission quota of 30.
![image](https://github.com/AISG-Technology-Team/GCSS-Track-1A-Submission-Guide/assets/44371415/ac3095cf-5b72-4000-beb5-eedd100e2efa)

**Comment by aisg-py** [comment]
Please be assured that we do not remove any part of your submitted JSON file when it is fed into by the victim LLMs.

We strictly adhere to the submission guideline _clause 7F_ as detailed in the [Terms and Conditions](https://gcss.aisingapore.org/terms-and-conditions). 

Additionally, while _clause 7E_ outlines that teams are entitled to a maximum of thirty (30) submissions throughout each Track phase, it is regulated by the aforementioned submission frequency detailed in _clause 7F_.
