### ISSUE TITLE
[USTC-Sec] - [matr1x] - [Why does the Llama-2-7b-chat-hf (ASR) score 0?]

### ISSUE THREAD

**Issue by hacker-jerry** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#6]
Hello, we noticed that Llama-2-7b-chat-hf (ASR) has many teams with a score of 0. This is not intuitive as it was able to trigger the vulnerability consistently when tested locally, and wondered if it is possible to view the model output and if it is running out of steam?

**Comment by aisg-py** [comment]
Hi @hacker-jerry , 

We keep model outputs private to ensure fairness and maintain the integrity of the competition. We continuously monitor all submissions and system performance. Thank you for your understanding.
