### ISSUE TITLE
[Team-Badass] - [charlesli2002] - [Regarding evaluation protocal]

### ISSUE THREAD

**Issue by Charles20021201** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#7]
Hi,

thanks for holding such a wonderful contest! I am having great fun participating in it.

My last submission achieves an ASR of 40.00 for Llama2 and 48.00 for Vicuna.

However, in my local test environment, where a Llama2-13B from HarmBench is used as the evaluator and greedy decoding is used for the two LLMs, the ASR is 88.00 and 90.00 respectively for the 50 behaviors provided. 

The transferability of the baseline GCG from Llama2 to Vicuna is also much lower than expected (only 16.00), given that Vicuna is a model extremely vulnerable to attack.

My main question is that the two models seem much more robust than we thought. So are there any defenses/tricks not mentioned in the game rules being applied to the models? Also, is the evaluator GPT-4?

Please forgive me if my questions are against the rules and all responses would be appreciated.

Lastly, thanks for your effort in holding this contest!

Best,
Charles

**Comment by Charles20021201** [comment]
@aisg-py

**Comment by aisg-py** [comment]
Hi @Charles20021201 , 

Thank you for participating in this challenge.

Regarding your query, please be assured that the models used in the competition are exactly as specified in the [Submission Guide](https://github.com/AISG-Technology-Team/GCSS-Track-1A-Submission-Guide). 

At this time, we're unable to provide specific details about the Judge LLM to ensure the integrity and fairness of the competition. We appreciate your understanding.

**Comment by Charles20021201** [comment]
Hi,

Thanks for your quick reply!

I am fully aware that the weights are exactly the same.

But would you be so kind as to share some information on the question that **_are there any defenses/tricks not mentioned in the game rules being applied to the models?_**

Best,
Charles

**Comment by Charles20021201** [comment]
@aisg-py

**Comment by mtmak-aisg** [comment]
@Charles20021201 , please do not double post.  If you intend to ping someone directly, kindly _edit_ your comment and add the ping.

**Comment by Charles20021201** [comment]
> @Charles20021201 , please do not double post. If you intend to ping someone directly, kindly _edit_ your comment and add the ping.

Ohh sorry for that.

**Comment by aisg-py** [comment]
Hi @Charles20021201 , 
All essential information required for successful participation in the challenge has already been provided on the challenge portal and submission guide.

**Comment by Charles20021201** [comment]
> Hi @Charles20021201 , All essential information required for successful participation in the challenge has already been provided on the challenge portal and submission guide.

Hi,
thanks for your reply! I have no other questions.
