### ISSUE TITLE
[CaelumArs] - [Leqi] - [Team merge]

### ISSUE THREAD

**Issue by leileqiTHU** [AISG-Technology-Team/GCSS-Track-1A-Submission-Guide#9]
Hey, thanks for holding this competition.

We are students from a same research group, planning to join the competition.
However, we accidentally created two teams without clear communication, with me being the sole member of one team. Currently, I haven't made any submissions yet. Can I delete my account and register a new one to join my teammates' team?

Best regards,
Leqi

**Comment by aisg-py** [comment]
Hi @leileqiTHU , 

Could I have the team name of the team you would like to join, for our consideration, please?

**Comment by leileqiTHU** [comment]
> Hi @leileqiTHU ,
> 
> Could I have the team name of the team you would like to join, for our consideration, please?

Sure! My team name is [CaelumArs] and the team I would like to join is [ModelCrackers].

**Comment by aisg-py** [comment]
Hi @leileqiTHU , 

To join the team ModelCrackers, please create a new account and inform us of the new username. 

Kindly note that your existing account should **not** be used for any submissions. 

Violation of the above will be deemed as a disqualifying behavior.

Please acknowledge this message before creating your new account. 

Thank you.

**Comment by mtmak-aisg** [comment]
> Violation of the above will be deemed as a disqualifying behavior.

For the sake of clarity, the disqualification, should it need to be applied, will be at the _team_ level, not the individual.

**Comment by aisg-py** [comment]
Hi @leileqiTHU , 
A quick reminder: Please create your new account for the team ModelCrackers and inform us of the username. Your existing account should not be used for any submissions. Kindly acknowledge this message before creating your new account to avoid disqualification.

Thank you.

**Comment by leileqiTHU** [comment]
Hey, sorry for the late reply!
My new username is Ars
I have abandoned my old username Leqi and never used that for submissions
thanks for your work!

**Comment by aisg-py** [comment]
Hi @leileqiTHU ,

We noticed you have created a new account and joined the team ModelCrackers without prior acknowledgment of our GitHub instructions. This action could typically result in disqualification. However, we will not take any action this time.

Please ensure future compliance with all guidelines to avoid any complications.

**Comment by leileqiTHU** [comment]
Hi,
I sincerely apologize for not acknowledging the instructions prior to creating the account and joining the team. 

I understand the importance of following the guidelines and will ensure strict compliance in the future. 

Thank you so much for your understanding and leniency this time.
